### PR TITLE
Square root ising

### PR DESCRIPTION
**Pull request by JoeyT1994**
Added Functions to `specialitensornetworks.jl` for creating the Tensor Network State corresponding to the square root of the classical ising partition function.

Also:

i) Removed a repeated docstring.
ii) Specified the link_space argument in `ising_network` so it works for both an index network with siteinds and without.

### CODE REVIEW

**Comment by mtfishman** [comment]
@JoeyT1994 looks like this broke a BP test.

**Comment by JoeyT1994** [comment]
Okay I see. I fixed it now with the latest commit.

**Comment by mtfishman** [comment]
Maybe `ising_network_state` would be a better name? `square_root` doesn't seem quite right for this (it's more that it is a sate such that the norm of the state gives the Ising model).

**Comment by mtfishman** [comment]
Thanks Joey, this will be very nice to have!

**Pull request merged**
