### PR TITLE
Add `weights(::AbstractITensorNetwork)`, new graph partitioning interface

### PR DESCRIPTION
**Pull request by mtfishman**
Also add examples for Graphs.jl functionality implemented in https://github.com/mtfishman/NamedGraphs.jl/pull/20 and https://github.com/mtfishman/DataGraphs.jl/pull/10.

### CODE REVIEW

**Comment by mtfishman** [comment]
`weights(tn::AbstractITensorNetwork)` is defined as `log2(dim(commoninds(tn, edge)))` for each `edge in edges(tn)`, and are stored in a `Dictionary`. This is the same definition used in https://arxiv.org/abs/2209.02895. This makes sense in the limit when `dim(commoninds(tn, edge)) == 1`, then the tensors are not connected and by this definition the weight is zero. Users can of course use their own function to compute weights for particular use cases, and pass the weights as necessary into graph functions that will use them.

@LinjianMa I think this is also what you are using?

**Comment by LinjianMa** [comment]
yes this is the one I’m using

**Comment by mtfishman** [comment]
In the latest I made some changes to the partition interface. The new syntax is summarized below:

```julia
julia> using ITensorNetworks

julia> tn = ITensorNetwork(named_grid((4, 2)); link_space=3);
```

`subgraph_vertices` returns a list of subgraph vertices according to the specified partitioning:
<details><summary>subgraph_vertices</summary><p>

```julia
julia> tn_sv = subgraph_vertices(tn; npartitions=2) # Same as `partition_vertices(tn; nvertices_per_partition=4)`
2-element Vector{Vector{Tuple{Int64, Int64}}}:
 [(1, 1), (2, 1), (1, 2), (2, 2)]
 [(3, 1), (4, 1), (3, 2), (4, 2)]
```

</p></details>

`partition_vertices` returns a graph with subgraph vertices as the vertex data and edges defining which subgraphs are connected according to the specified partitioning:
<details><summary>partition_vertices</summary><p>

```julia
julia> tn_pv = partition_vertices(tn; npartitions=2);

julia> typeof(tn_pv)
DataGraph{Int64, Vector{Tuple{Int64, Int64}}, Any, NamedGraphs.NamedGraph{Int64}, NamedGraphs.NamedEdge{Int64}}

julia> tn_pv[1]
4-element Vector{Tuple{Int64, Int64}}:
 (1, 1)
 (2, 1)
 (1, 2)
 (2, 2)

julia> edges(tn_pv)
1-element Vector{NamedGraphs.NamedEdge{Int64}}:
 1 => 2

julia> tn_pv[1 => 2]
2-element Vector{NamedGraphs.NamedEdge{Tuple{Int64, Int64}}}:
 (2, 1) => (3, 1)
 (2, 2) => (3, 2)
```

</p></details>

`subgraphs` returns a list of subgraphs according to the specified partitioning:
<details><summary>subgraphs</summary><p>

```julia
julia> tn_sg = subgraphs(tn; npartitions=2);

julia> typeof(tn_sg)
Vector{ITensorNetwork{Tuple{Int64, Int64}}} (alias for Array{ITensorNetwork{Tuple{Int64, Int64}}, 1})

julia> tn_sg[1]
ITensorNetwork{Tuple{Int64, Int64}} with 4 vertices:
4-element Vector{Tuple{Int64, Int64}}:
 (1, 1)
 (2, 1)
 (1, 2)
 (2, 2)

and 4 edge(s):
(1, 1) => (2, 1)
(1, 1) => (1, 2)
(2, 1) => (2, 2)
(1, 2) => (2, 2)

with vertex data:
4-element Dictionaries.Dictionary{Tuple{Int64, Int64}, Any}
 (1, 1) │ ((dim=3|id=169|"1×1↔2×1"), (dim=3|id=124|"1×1↔1×2"))
 (2, 1) │ ((dim=3|id=169|"1×1↔2×1"), (dim=3|id=105|"2×1↔3×1"), (dim=3|id=352|"2×1↔2×2"))
 (1, 2) │ ((dim=3|id=124|"1×1↔1×2"), (dim=3|id=789|"1×2↔2×2"))
 (2, 2) │ ((dim=3|id=352|"2×1↔2×2"), (dim=3|id=789|"1×2↔2×2"), (dim=3|id=254|"2×2↔3×2"))
```

</p></details>

`partition` returns a graph with subgraphs as the vertex data and edges defining which subgraphs are connected according to the specified partitioning:
<details><summary>partition</summary><p>

```julia
julia> tn_pg = partition(tn; npartitions=2);

julia> typeof(tn_pg)
DataGraph{Int64, ITensorNetwork{Tuple{Int64, Int64}}, Any, NamedGraphs.NamedGraph{Int64}, NamedGraphs.NamedEdge{Int64}}

julia> tn_pg[1]
ITensorNetwork{Tuple{Int64, Int64}} with 4 vertices:
4-element Vector{Tuple{Int64, Int64}}:
 (1, 1)
 (2, 1)
 (1, 2)
 (2, 2)

and 4 edge(s):
(1, 1) => (2, 1)
(1, 1) => (1, 2)
(2, 1) => (2, 2)
(1, 2) => (2, 2)

with vertex data:
4-element Dictionaries.Dictionary{Tuple{Int64, Int64}, Any}
 (1, 1) │ ((dim=3|id=169|"1×1↔2×1"), (dim=3|id=124|"1×1↔1×2"))
 (2, 1) │ ((dim=3|id=169|"1×1↔2×1"), (dim=3|id=105|"2×1↔3×1"), (dim=3|id=352|"2×1↔2×2"))
 (1, 2) │ ((dim=3|id=124|"1×1↔1×2"), (dim=3|id=789|"1×2↔2×2"))
 (2, 2) │ ((dim=3|id=352|"2×1↔2×2"), (dim=3|id=789|"1×2↔2×2"), (dim=3|id=254|"2×2↔3×2"))

julia> tn_pg[1 => 2][:edges]
2-element Vector{NamedGraphs.NamedEdge{Tuple{Int64, Int64}}}:
 (2, 1) => (3, 1)
 (2, 2) => (3, 2)
```

</p></details>

@JoeyT1994 let me know what you think. Should supersede #34 and close #28.

Also, the example of partitioning a partitioned graph discussed in #28 can now be done with:
```julia
using ITensors
using Graphs
using NamedGraphs
using ITensorNetworks
using SplitApplyCombine
using Metis

s = siteinds("S=1/2", named_grid(8))
tn = ITensorNetwork(s; link_space=2)
Z = prime(tn; sites=[]) ⊗ tn
vertex_groups = group(v -> v[1], vertices(Z))
# Create two layers of partitioning
Z_p = partition(partition(Z, vertex_groups); nvertices_per_partition=2)
# Flatten the partitioned partitions
Z_verts = [reduce(vcat, (vertices(Z_p[vp][v]) for v in vertices(Z_p[vp]))) for vp in vertices(Z_p)]
```
which can be found in `examples/group_partition.jl`.

**Comment by JoeyT1994** [comment]
Hi Matt,

This looks great to me. Being able to stack partitioning like that is really helpful for memory efficient generalized belief propagation.

I will close PR #34 as I believe this supercedes it.

In early Jan I will create a PR 2 for belief propagation where the example and test takes advantage of this interface. I will also improve the mechanism for calculating expectation values.

**Pull request merged**
